services:
  database:
    container_name: database_container
    image: better-sqlite3
    build:
      context: .
      target: development
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
      DATABASE_FILE_PATH: "file:/app/server/database/database.db" # or the regular file?
    volumes:
      - database_data:/app/server/database
      - ./server:/app/server  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
      - ./uploads:/app/uploads
    tty: true
    healthcheck:
      test: ["CMD", "test", "-f", "/app/server/database/database.db"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  database_data:

